# Generated by Django 4.2.3 on 2023-11-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.user"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(to="news.category"),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(),
        ),
    ]
